

// AUTOGENERATED DO NOT EDIT

namespace BlazorMeetsReact.React
{
    public enum ReactComponent
    {
        Divider,
        Greeting,
        NestedComponent,
        SimpleComponent,
        
    }
}
