

// AUTOGENERATED DO NOT EDIT

import ReactDOM from 'react-dom';
import React from 'react';

import { Divider } from './Divider'
import { Greeting } from './Greeting'
import { NestedComponent } from './NestedComponent'
import { SimpleComponent } from './SimpleComponent'

    

(window as any).renderReact = function (componentName: string, props: any, renderElement: HTMLElement)
{
    const reactComponents: { [key: string]: JSX.Element } = {};
    
    reactComponents['Divider'] = <Divider {...props}/>;
    reactComponents['Greeting'] = <Greeting {...props}/>;
    reactComponents['NestedComponent'] = <NestedComponent {...props}/>;
    reactComponents['SimpleComponent'] = <SimpleComponent {...props}/>;
    
    
    ReactDOM.render(reactComponents[componentName], renderElement);

};